services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: my_redis_db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge   
volumes:
  postgres_data: {}
